{
 "title": "Home Devices",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "alertlist",
   "description": "List of dashboard alerts for the apartment.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 }
  },
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Current House State",
   "type": "singlestat",
   "description": "Current state of the house.  Modes trigger different levels of automation.  Changes in modes are annotated automatically on the graphs.\n\nPossible modes:\n\nHome - Someone is currently home.\n\nAway - Everyone in the house is away.\n\nNight - Everyone is asleep.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "_stMode",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "description": "Last status of all users in the house",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "locationName" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "presence",
     "query": "SELECT last(\"value\") FROM \"presence\" WHERE $timeFilter GROUP BY time($__interval), \"deviceName\", \"locationName\" LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Thermostat State",
   "type": "singlestat",
   "description": "The current state of the thermostat.  Either idle, heating, or cooling.",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "thermostatOperatingState",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Average house temperature, in Fahrenheit.",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 7 },
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Main Thermostat" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "description": "Average house humidity level",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 7 },
   "targets": [
    {
     "measurement": "humidity",
     "query": "SELECT last(\"value\") FROM \"temperature\" WHERE deviceName = \"Nest Thermostat - Den\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "!=", "value": "Living Room" },
      { "condition": "AND", "key": "deviceName", "operator": "!=", "value": "Weather" },
      { "condition": "AND", "key": "deviceName", "operator": "!=", "value": "AccuWeather (22031)" }
     ]
    }
   ]
  },
  {
   "title": "Carbon Monoxide Status",
   "type": "singlestat",
   "description": "Current Carbon Monoxide Status for the house.",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 7 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "carbonMonoxide",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Levels",
   "type": "table",
   "description": "Levels of Batteries for different IOT devices",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "battery",
     "query": "SELECT last(\"value\") FROM \"battery\" WHERE $timeFilter GROUP BY time($__interval), \"deviceName\" LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "!=", "value": "Living Room" }
     ]
    }
   ]
  },
  { "title": "Doors and Windows Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Doors",
   "type": "table",
   "description": "Current state of all locks",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "measurement": "lock",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Window Status",
   "type": "table",
   "description": "Status of all windows in the house.",
   "gridPos": { "h": 9, "w": 3, "x": 5, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "measurement": "contact",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "!=", "value": "Fridge Sensor" }
     ]
    }
   ]
  },
  {
   "title": "Doors",
   "type": "graph",
   "description": "Graph of all door states.  0 means locked.",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of time open" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "measurement": "lock",
     "select": [
      [
       { "params": [ "valueBinary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  { "title": "Lights and Other Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Light Levels",
   "type": "graph",
   "description": "Brightness of the lights, in percentage.  \n\nCurrently not displaying what I want, as lights that are \"off\" just show their last brightness, instead of \"0%\".  Might remove because of it.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch",
     "query": "SELECT mean(\"valueBinary\") FROM \"switch\" WHERE (\"deviceName\" =~ /Lights/) AND $timeFilter GROUP BY time($__interval), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "valueBinary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Lights" }
     ]
    }
   ]
  },
  {
   "title": "TV State",
   "type": "graph",
   "description": "What \"mode\" the TV is in, aka what Harmony activity is on.  Should default to \"Echo\" when I am home and awake, and all modes should be \"off\" when asleep or away.",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch",
     "select": [
      [
       { "params": [ "valueBinary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "TV" }
     ]
    }
   ]
  },
  {
   "title": "Light State",
   "type": "table",
   "description": "Current light states for each room.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "measurement": "switch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/Lights/" }
     ]
    }
   ]
  },
  {
   "title": "Smoke Alarms",
   "type": "table",
   "description": "Table of last smoke alarm status.",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "measurement": "smoke",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lux",
   "type": "graph",
   "description": "Lux Levels of each room.",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Lux" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "illuminance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Power Outlets",
   "type": "graph",
   "description": "Power draw of outlets, in Watts (W).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "description": "Power used over time, in Kilowatt-Hour",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Cost",
   "type": "table",
   "description": "Breakdown on the current cost of each power outlet",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 53 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*0.12" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Thermostat Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Current Thermostat State",
   "type": "singlestat",
   "description": "The current state of the thermostat.  Either idle, heating, or cooling.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 63 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "thermostatOperatingState",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Thermostat Mode",
   "type": "singlestat",
   "description": "Mode the thermostat is set to.\n\nHeat - Just heat if below a threshold\n\nCool - Just cool if above a threshold\n\nAuto - Heat if below a threshold or Cool is above a threshold\n\nOff - Thermostat is off",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 63 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "thermostatMode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Thermostat Fan Mode",
   "type": "singlestat",
   "description": "Shows the current state of the HVAC's fan\n\nAuto - Automatic Fan Mode\n\nOn - Fan is On",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 63 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "thermostatFanMode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature and Thresholds",
   "type": "graph",
   "description": "Graph of the apartment's temperature and heating/cooling thresholds.\n\nTemperature - The apartment's measured temperature\n\nCooling Threshold - When the temperature is above this, HVAC enters 'cooling' mode\n\nHeating Threshold - When the temperature is below this, HVAC enters 'heating' mode",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 63 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Main Thermostat" }
     ]
    },
    {
     "alias": "Cooling Threshold",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "coolingSetpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Main Thermostat" }
     ]
    },
    {
     "alias": "Heating Threshold",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heatingSetpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Main Thermostat" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "description": "Graph of the house's humidity, in percentage",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Indoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "!=", "value": "Living Room" },
      { "condition": "AND", "key": "deviceName", "operator": "!=", "value": "Weather" }
     ]
    },
    {
     "alias": "Outdoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Weather" }
     ]
    }
   ]
  },
  { "title": "Thermostat Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Temperatures per Room",
   "type": "graph",
   "description": "Graph of the house's temperature per room.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Main Thermostat" },
      { "condition": "OR", "key": "deviceName", "operator": "=", "value": "Basement" }
     ]
    }
   ]
  },
  {
   "title": "Humidity per Room",
   "type": "graph",
   "description": "Graph of the house's humidity per room.",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "!=", "value": "Living Room" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "description": "Temperature, broken down by location.",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 72 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Main Thermostat" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "table",
   "description": "Humidity, broken down by location.",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 72 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "!=", "value": "Main Thermostat" }
     ]
    }
   ]
  },
  {
   "title": "Thermostat State",
   "type": "graph",
   "description": "Shows the state of the thermostat over time. \n\nIdle - HVAC is off\n\nHeating - HVAC is heating\n\nCooling - HVAC is cooling",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Heating",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "thermostatOperatingState",
     "select": [
      [
       { "params": [ "valueBinary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "deviceName", "operator": "=", "value": "Main Thermostat" }
     ]
    },
    {
     "alias": "Cooling",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thermostatOperatingState",
     "select": [
      [
       { "params": [ "valueBinary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=", "value": "cooling" },
      { "condition": "AND", "key": "deviceName", "operator": "=", "value": "Main Thermostat" }
     ]
    },
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "thermostatOperatingState",
     "select": [
      [
       { "params": [ "valueBinary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "deviceName", "operator": "=", "value": "Main Thermostat" }
     ]
    }
   ]
  },
  {
   "title": "Fan Activity",
   "type": "graph",
   "description": "Fan activity over time",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "percentunit", "label": "State" }
   ],
   "targets": [
    {
     "alias": "Fan Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "thermostatFanMode",
     "select": [
      [
       { "params": [ "valueBinary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=", "value": "on" }
     ]
    }
   ]
  },
  {
   "title": "Hidden for alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery Levels",
     "type": "graph",
     "description": "Battery Levels for any devices that run off a battery.",
     "gridPos": { "h": 7, "w": 3, "x": 1, "y": 90 },
     "yaxes": [
      { "format": "percent", "label": "Battery Level" }
     ],
     "targets": [
      {
       "alias": "$tag_deviceName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "deviceName" ], "type": "tag" }
       ],
       "measurement": "battery",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Motion - Hide this graph",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 4, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_deviceName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "deviceName" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "motion",
       "select": [
        [
         { "params": [ "valueBinary" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "deviceName", "operator": "!=", "value": "Basement Motion Sensor" },
        { "condition": "AND", "key": "deviceName", "operator": "!=", "value": "Nest Camera - Front Door" }
       ]
      }
     ]
    }
   ]
  }
 ]
}