apiVersion: v1
data:
  helm.repositories: |
    - url: https://raw.githubusercontent.com/bstascavage/dex-k8-authenticator-repo/master
      name: mintel
  oidc.config: |
    name: Google
    issuer: https://dex.felannisport.com
    clientID: dex-secret-argocd
    clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
  repositories: |
    - passwordSecret:
        key: password
        name: repo-felannisport-helm-3834629330
      url: https://github.com/bstascavage/felannisport-helm
      usernameSecret:
        key: username
        name: repo-felannisport-helm-3834629330
  url: https://argocd.felannisport.com
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"argocd-cm","namespace":"argocd"}}
  name: argocd-cm
  namespace: argocd
  selfLink: /api/v1/namespaces/argocd/configmaps/argocd-cm
