# Default values for dex
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 1

service:
  type: LoadBalancer

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt-dex
    kubernetes.io/ingress.class: "nginx"
  path: /
  hosts:
    - dex.felannisport.com
  tls:
    - secretName: letsencrypt-dex-tls
      hosts:
        - dex.felannisport.com

serviceAccount:
  create: true
  name: dex-auth-sa

config:
  issuer: https://dex.felannisport.com
  storage:
    type: kubernetes
    config:
      inCluster: true
  logger:
    level: debug
  web:
    http: 0.0.0.0:8080
  grpc:
    addr: 0.0.0.0:5000
  frontend:
    theme: "coreos"
    issuer: "Felannisport SSO"
    issuerUrl: "https://felannisport.com"
    logoUrl: https://felannisport.com/images/logo-250x25.png
  expiry:
    signingKeys: "6h"
    idTokens: "24h"
  logger:
    level: debug
    format: json
  oauth2:
    responseTypes: ["code", "token", "id_token"]
    skipApprovalScreen: true
  connectors:
  - type: oidc
    id: google
    name: Google
    config:
      issuer: https://accounts.google.com
      clientID: "70925338276-1bd3q778hgj4konlhrculovv0ttng1f4.apps.googleusercontent.com"
      clientSecret: "6W21kd_P8arp2f2hlOQuLfGm"
      redirectURI: https://dex.felannisport.com/callback
      hostedDomains:
        - stascavage.com
#  - type: github
#    id: github
#    name: GitHub
#    config:
#      clientID: xxxxxxxxxxxxxxx
#      clientSecret: yyyyyyyyyyyyyyyyyyyyy
#      redirectURI: https://dex.minikube.local:5556/callback
#      org: kubernetes

  staticClients:
  - id: dex-secret
    name: dex-secret
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    redirectURIs:
    - "https://login.felannisport.com/callback/"
  - id: dex-secret-argocd
    name: dex-argocd
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    redirectURIs:
    - "https://argocd.felannisport.com/auth/callback"
    - "http://localhost:8085/auth/callback"
  - id: dex-grafana
    name: dex-grafana
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0sdleojfdpoounwes
    redirectURIs:
    - "https://grafana.felannisport.com/login/generic_oauth"

  enablePasswordDB: true
# staticPasswords:
#  - email: "admin@example.com"
#    # bcrypt hash of the string "password"
#    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
#    username: "admin"
#    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
envSecrets:
  # Google (oidc)
  GOOGLE_CLIENT_ID: "70925338276-1bd3q778hgj4konlhrculovv0ttng1f4.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "6W21kd_P8arp2f2hlOQuLfGm"
